# Generated by Django 2.1.2 on 2019-04-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataEntrySystem', '0002_auto_20190416_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target_company_package',
            name='pdf_id',
        ),
        migrations.AddField(
            model_name='target_company_package',
            name='pdf',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='DataEntrySystem.pdf_information'),
        ),
    ]
